language: python
python: 3.7
install:
- pip3 install -r requirements.txt
script:
- gem install dpl
- dpl --provider=heroku --app=leopoll --api-key=$HEROKU_API_KEY
env:
  global:
    secure: UHVKhGFHr1cG7iPK0F63JmnlvrBiX09cCtmuXWugxlUKcnpDccMzNY94fZ5ZIDMXQaWmJgFsA78nkp94ym0H1v21icBdYY72HhVzzXeZea5Kk5lp91Kk5vLSKmKyDuWUEMxPEUNQvi5nN5lG8f2slYkiZccRw+MlW43U65A2n4YADhUTHwhSHmhlJH+YjjVHK3kItpa/Z03pEqj89RHdDKeEYE3MDrPcJmxD3QaMKSoNXS5TMc14IPrH6trJCRhuQGaw6R2w3YPAPMoLsQJ4P0L0DBWG8/nLjknqKJSTKnnyTW9eGn32JKkUjfJsLb7mffEx6bLbbGjyrEW6o/nR+eJh7ixMrWArp9IS2SsDfyQAiklHWOVB+mdX4q0amgmYojfDwSu1UfMSNVrQGc47tgaRR4GNzOe5I828f0q+hSkIuoBXzHLg5OPGajK1rMZUN7jlbT1btA8px9Z6gGOmgnN8FAqfJfpPoPqqytoLhJVb0wiecDU8h9PNNHbp4OICcHIvWydVrxke5qOwbGyR+gYhrG/KJQ8G9KEHnSQ3s4NzgaxXBPECJms0qILPZr6nlOQ23isHukZZDUCzI4AVEaom0scWX26czJ+XUcNf5uF1yMMapItFWvbQiyDSnFEq0RQrLG5nLV+1gMvL1vO56ym9Pxrm9TNhXHZsugOQaPE=
notifications:
  slack:
    secure: mvhhkNx30LR8Msz6OzoEi0kIJwLn2Hx05jAgqvt+5Mo1MxM/IdGB0pOfuoZquXOXelpaJbCjQyLQvF2PLKUpBEN6En+01PlJDTj6yr0QoLX7iDvtObK0S5ZFI27Z74L6KZif1nplC+Sz9qZ1W6jFWQVv62SDYkBGwDJWqkTCEp58OFTcDJuvUBLoGXGUb/f1MqFngORnAZ5ezM+0PM4F6jE4RhM2Ghapyu7gB45p7qcngfFhrFQUBGlAnH/ir7rzYMHt0oEJYsdkONoMU5Y2pvSjaJm7wRa0gX+2McG8VfbvIpxt6KvnErRfGeMC/r4B6guUEuIBe8C6P8hrBiwCg0wbnWsyJz+BMd1+6IpxrtuDgHl4VwkJR7l5ZFrAY4JqmnV2D3TbULaZfgeaI823XVSYW7MpnLEgOLGmnmVC/swucBeOnMCpqCsdqHwjE0MzKippu0nffkCvjfin7VRxEZsp2A/0nNx+PQhkjMVZLTm2mLHoP1MKFtz13EBxpUMeOH2A/+sHXGa+dXqbBZe2Al0G7mOtI66AQV6mXYX/Pmo5tnF1ZdrcMfQG1J/MXGDOYXcuPyv2L7bZosG7Q2UPztg7ow7u1GFCjmGP0SoXs2m2AD0827n8IPDEe7wnrans9eLkJBH5OJ4MfpAxQBCv/8Mj2hXEq/3DQY0UuLNF2x4=
